### PR TITLE
Initial test setup

### PR DESCRIPTION
**Pull request by sofiaedstrom**
Local setup for both e2e and unit tests 

e2e: Nightwacth + Selenium
unit: Nightwatch

* tiny e2e test
* dummy unit test
* execute 'npm test' to run both test suites

### CODE REVIEW

**Comment by Doverstav** [comment]
Should probably be merged into develop and not master.

**Comment by sofiaedstrom** [comment]
Yes, most certainly! 😄

**Review by Doverstav — COMMENTED** [review]
Add some small documentation in README (how to run, basically), and perhaps add npm start to 'test'-script so that command is the only one you have to run.

**Comment by sofiaedstrom** [comment]
fixed the comments, merging! :shipit:

**Pull request merged**
